部署到杭州办公测试环境:
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run docs
    - rm -rf /data/www/fed-docs/hekr-components/*
    - cp -R docs/* /data/www/fed-docs/hekr-components/
  tags:
    - hz-test
  only:
    - master
  when: always
  environment:
    name: 10.10.1.2
    url: http://10.10.1.2:7777/hekr-components/index.html
